name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests (basic Flask import check)
        run: |
          python -c "from flask import Flask; print('✅ Flask import successful')"

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t consignment-flask-api .

      - name: Test Docker container (run Flask)
        run: |
          docker run -d -p 5000:5000 --name test-container consignment-flask-api
          sleep 5
          docker ps
          docker logs test-container
          docker stop test-container
