name: Model Monitoring

on:
  schedule:
    - cron: "0 0 * * 0"   # Runs weekly
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install evidently pandas scikit-learn

      - name: Run monitoring script
        run: |
          python src/monitor.py
